kind: Service
apiVersion: v1
metadata:
  name: app1-service
  namespace: app1-namespace
spec:
  selector:
    app: app1-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31101